accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'), #http://127.0.0.1:8000/accounts/signup/
    url(r'^testing/$', views.testing_view, name='testing') #http://127.0.0.1:8000/accounts/testing/
]

blogPost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # fix this to deploy with heroku
    url(r'^$', views.homepage),
    url(r'^accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

accounts/forms.py
from django import forms
from .import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MyRegistrationForm(UserCreationForm):
    """docstring for RegistrationForm."""
    email = forms.EmailField(required=True)

    class Meta:
        """docstring for Meta ."""
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
            )

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)

        if commit:
            user.save()

        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from accounts.forms import MyRegistrationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:testing')
    else:
        form = MyRegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def testing_view(request):
    return render(request, 'accounts/testing.html')

blogPost/views.py
from django.shortcuts import render
import requests


#homepage
def homepage(request):
    return render(request, "index.html")

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create Account</title>
  </head>
  <body>

    <div class="container-fluid">
    <div class="container">
      <h1>Signup</h1>
      <form class="mdl-textfield mdl-js-textfield" action="{% url 'accounts:signup'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" required>
        <label class="form-check-label" for="defaultCheck1">I accept the terms and conditions.</label>
        <br>
        <br>
        <button class="btn btn-primary" type="submit">Next</button>
      </form>
    </div>
  </div>

  </body>
</html>

accounts/templates/accounts/testing.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Home</h1>
  </body>
</html>

templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Meal Blog Site Coming Soon</title>

    <!-- MAIN CSS -->
    <link href="{% static 'master.css' %}" rel="stylesheet">

    <!-- BOOTSTRAP CSS -->
    <link href="{{ STATIC_URL }} https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- FONT AWESOME -->
    <!-- <link href="{{ STATIC_URL }} fontawesome.css" rel="stylesheet">
    <link href="{{ STATIC_URL }} brands.css" rel="stylesheet">
    <link href="{{ STATIC_URL }} solid.css" rel="stylesheet"> -->

    <!-- ANIMATE -->
    <link href="{{ STATIC_URL }} https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" rel="stylesheet">


  </head>
  <body>
    <section class="border">
      <div class="container-fluid">
        <div class="col-lg-12 col-sm-12">
          <h2 class="comingSoonText animate__animated animate__backInDown animate__delay-3s">Coming Soon!</h2>
        </div>
        <hr>
        <hr>
        <hr>
        <div class="col-lg-12 col-sm-12">
          <h2 class="introFont">College Students Quick Meal Stop</h2>
        </div>
        <hr>
        <div class="col-lg-12">
          <h2 class="aboutFont">Find recipes made by your peers at various universities</h2>
        </div>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'accounts:signup' %}">Login</a>
      </div>

      <img class="comingSoonImg" src="{% static 'foodItems.jpeg' %}" alt="">

    </section>

    <script rel="stylesheet" href="{% static 'master.js' %}"></script>

  </body>
</html>